default_language_version:
  python: python3.11

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort .
        language: python
        types: [python]
