[tool.poetry]
name = "toggl_python"
version = "0.2.8"
description = "Python wrapper for Toggl API."
authors = ["Ivlev Denis <me@dierz.pro>"]
readme = "README.md"
homepage = "https://github.com/evrone/toggl_python"
repository = "https://github.com/evrone/toggl_python"
documentation = "https://toggl-python.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras=["http2"], version="^0.17.1"}
pydantic = {extras = ["email"], version = "^1.7.2"}

[tool.poetry.dev-dependencies]
pytest = "^6.2"
respx = "^0.16"
black = "^20.8b1"
ipython = "^7.21.0"
mypy = "^0.812"
coverage = "^5.5"
flake8 = "^3.9.0"
isort = "^5.8.0"
pre-commit = "^2.11.1"

[tool.black]
line-length = 100
target-version = ['py38']
exclude = '''
(
  \.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
)
'''

[tool.isort]
line_length = 100
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
known_django = "django"
profile = "django"
src_paths = "toggl_python"
lines_after_imports = 2

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"